apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: samba-ad-admin
  namespace: samba-ad
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: samba-ad-admin
    creationPolicy: Owner
  data:
    - secretKey: DOMAINPASS
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: samba-ad
        metadataPolicy: None
        property: admin-pass
