apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: music-downloader
  namespace: pedals
spec:
  parentRefs:
    - name: main-gateway
      namespace: kube-system
  hostnames:
    - "downloader.k8s.benrachmiel.org"
  rules:
    - backendRefs:
        - name: music-downloader
          port: 4180
