# External Secrets Operator
# Install with:
#   helm install external-secrets external-secrets/external-secrets -n external-secrets --create-namespace -f external-secrets-values.yaml

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi

webhook:
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi

certController:
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 64Mi
