image:
  tag: sha-46602fa

ui:
  enabled: true
  image:
    tag: sha-46602fa
  oauthProxy:
    issuerURL: https://dex.k8s.benrachmiel.org
    clientID: preamp
    extraArgs:
      - --email-domain=*

config:
  collectorTokenEnabled: true

gateway:
  enabled: true
  host: preamp.k8s.benrachmiel.org

persistence:
  music:
    existingClaim: preamp-music
  data:
    storageClass: ceph-rbd

secrets:
  existingSecret: preamp-secrets

extraObjects:
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: preamp-secrets
    spec:
      refreshInterval: 1h
      secretStoreRef:
        kind: ClusterSecretStore
        name: vault
      target:
        name: preamp-secrets
        deletionPolicy: Retain
      data:
        - remoteRef:
            key: preamp/secrets
            property: encryption-key
          secretKey: PREAMP_ENCRYPTION_KEY
        - remoteRef:
            key: preamp/secrets
            property: oauth2-client-secret
          secretKey: OAUTH2_PROXY_CLIENT_SECRET
        - remoteRef:
            key: preamp/secrets
            property: oauth2-cookie-secret
            decodingStrategy: None
          secretKey: OAUTH2_PROXY_COOKIE_SECRET
        - remoteRef:
            key: preamp/secrets
            property: collector-token
          secretKey: PREAMP_COLLECTOR_TOKEN
