apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarqube-oauth-secrets
  namespace: sonarqube
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: sonarqube-oauth-secrets
    creationPolicy: Owner
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: sonarqube/oauth
        metadataPolicy: None
        property: client-secret
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: sonarqube/oauth
        metadataPolicy: None
        property: cookie-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarqube-db-credentials
  namespace: sonarqube
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: sonarqube-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: sonarqube/database
        metadataPolicy: None
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: sonarqube/database
        metadataPolicy: None
        property: password
