apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-db-credentials
  namespace: mlflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: mlflow-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: mlflow/database
        property: username
    - secretKey: password
      remoteRef:
        key: mlflow/database
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-admin-credentials
  namespace: mlflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: mlflow-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: mlflow/admin
        property: username
    - secretKey: password
      remoteRef:
        key: mlflow/admin
        property: password
