apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak-test
spec:
  instances: 1
  enableSuperuserAccess: false
  storage:
    storageClass: ceph-rbd
    size: 5Gi
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-credentials
