apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak-test
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: keycloak-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: keycloak/database
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak/database
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak-test
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: keycloak-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: KC_BOOTSTRAP_ADMIN_USERNAME
      remoteRef:
        key: keycloak/admin
        property: username
    - secretKey: KC_BOOTSTRAP_ADMIN_PASSWORD
      remoteRef:
        key: keycloak/admin
        property: password
