apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: dex
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: dex-secrets
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dex/github-oauth
        metadataPolicy: None
        property: clientID
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dex/github-oauth
        metadataPolicy: None
        property: clientSecret
    - secretKey: ARGOCD_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dex/clients
        metadataPolicy: None
        property: argocd
    - secretKey: GRAFANA_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dex/clients
        metadataPolicy: None
        property: grafana
    - secretKey: MUSIC_DOWNLOADER_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dex/clients
        metadataPolicy: None
        property: music-downloader
    - secretKey: PREAMP_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dex/clients
        metadataPolicy: None
        property: preamp
    - secretKey: RIG_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dex/clients
        metadataPolicy: None
        property: rig
